// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlTviVZB-RRYCssOgWEBvh-dGOdzOIPOg',
    appId: '1:748328539260:web:b88bcf507a8ca261f225f9',
    messagingSenderId: '748328539260',
    projectId: 'lessonvault-ee31b',
    authDomain: 'lessonvault-ee31b.firebaseapp.com',
    storageBucket: 'lessonvault-ee31b.firebasestorage.app',
    measurementId: 'G-88JCPN04GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvB-wk-HKzRlsYqYn50Gz8ei4FapM8hgE',
    appId: '1:748328539260:android:a485883f4787567ff225f9',
    messagingSenderId: '748328539260',
    projectId: 'lessonvault-ee31b',
    storageBucket: 'lessonvault-ee31b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEBaG5-R5pmmGsPpKbkcm3WNramnGPpX0',
    appId: '1:748328539260:ios:08ab90e92f231556f225f9',
    messagingSenderId: '748328539260',
    projectId: 'lessonvault-ee31b',
    storageBucket: 'lessonvault-ee31b.firebasestorage.app',
    iosBundleId: 'com.example.lessonvault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEBaG5-R5pmmGsPpKbkcm3WNramnGPpX0',
    appId: '1:748328539260:ios:08ab90e92f231556f225f9',
    messagingSenderId: '748328539260',
    projectId: 'lessonvault-ee31b',
    storageBucket: 'lessonvault-ee31b.firebasestorage.app',
    iosBundleId: 'com.example.lessonvault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlTviVZB-RRYCssOgWEBvh-dGOdzOIPOg',
    appId: '1:748328539260:web:7731a63a66cb948bf225f9',
    messagingSenderId: '748328539260',
    projectId: 'lessonvault-ee31b',
    authDomain: 'lessonvault-ee31b.firebaseapp.com',
    storageBucket: 'lessonvault-ee31b.firebasestorage.app',
    measurementId: 'G-Q84JZHYKXV',
  );
}
